use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use hell_digest as digest;

const CATALOGS: &[(&str, &[&str])] = &[
    (
        "REQUIREMENT_CATALOG",
        &["compat", "requirements", "2026-05-29.toml"],
    ),
    ("CLAIM_RULES", &["compat", "claim-rules.toml"]),
    ("NORMALIZER_CATALOG", &["compat", "normalizers.toml"]),
    ("OBLIGATION_CATALOG", &["compat", "corpus-obligations.toml"]),
    ("DIVERGENCE_CATALOG", &["compat", "divergences.toml"]),
];

const REQUIREMENT_SCOPE_KEYS: &[&str] = &[
    "profiles",
    "platforms",
    "applicability_rule",
    "evidence_strategy",
    "evidence",
    "normalizers",
    "obligations",
    "rationale",
    "tracking_issue",
    "review_group",
];

const NORMALIZER_KEYS: &[&str] = &[
    "id",
    "variant",
    "implementation",
    "version",
    "allowed_dimensions",
    "allowed_fields",
    "forbidden_fields",
    "idempotent",
    "max_changed_values",
    "max_removed_bytes",
    "requires_platforms",
    "mutation_suite",
];

#[derive(Clone)]
struct Section {
    header: String,
    values: BTreeMap<String, String>,
}

#[derive(Clone)]
struct ClaimScope {
    profiles: Vec<String>,
    platforms: Vec<String>,
    evidence_strategy: String,
    evidence: Vec<String>,
    normalizers: Vec<String>,
    obligations: Vec<String>,
    applicability_rule: String,
    rationale: String,
    tracking_issue: String,
    review_group: String,
}

struct ClaimOverride {
    builtin: String,
    dimension: String,
    scopes: Vec<ClaimScope>,
}

struct Claims {
    baseline: String,
    default_scope: ClaimScope,
    overrides: Vec<ClaimOverride>,
}

struct Normalizer {
    id: String,
    variant: String,
    implementation: String,
    version: u64,
    allowed_dimensions: Vec<String>,
    allowed_fields: Vec<String>,
    forbidden_fields: Vec<String>,
    idempotent: bool,
    max_changed_values: u64,
    max_removed_bytes: u64,
    requires_platforms: Vec<String>,
    mutation_suite: String,
    implementation_sha256: String,
}

fn main() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let root = manifest
        .parent()
        .and_then(Path::parent)
        .expect("workspace root");
    let sources = load_catalog_sources(root);
    let implementation_path = root
        .join("crates")
        .join("hell-testkit")
        .join("src")
        .join("lib.rs");
    println!("cargo:rerun-if-changed={}", implementation_path.display());
    let implementation_source = fs::read(&implementation_path).unwrap_or_else(|error| {
        panic!(
            "cannot read normalizer implementation source {}: {error}",
            implementation_path.display()
        )
    });

    let normalizers = parse_normalizers(
        sources
            .get("NORMALIZER_CATALOG")
            .expect("normalizer catalog source"),
        &implementation_source,
    );
    let normalizer_ids = normalizers
        .iter()
        .map(|normalizer| normalizer.id.as_str())
        .collect::<BTreeSet<_>>();
    let obligation_source = sources
        .get("OBLIGATION_CATALOG")
        .expect("obligation catalog source");
    let obligation_ids = obligation_ids(obligation_source);
    let claims = parse_claims(
        sources
            .get("REQUIREMENT_CATALOG")
            .expect("requirement catalog source"),
        &normalizer_ids,
        &obligation_ids,
    );
    validate_flat_catalogs(&sources);

    let mut generated =
        String::from("// @generated by crates/hell-builtins/build.rs; do not edit.\n");
    for (name, _) in CATALOGS {
        writeln!(
            generated,
            "pub const {name}: &str = {:?};",
            sources.get(name).expect("catalog source")
        )
        .expect("write generated catalog");
    }
    emit_claims(&mut generated, &claims);
    emit_normalizers(&mut generated, &normalizers);
    emit_flat_constants(&mut generated, &sources);
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("output directory"))
        .join("assurance_catalogs.rs");
    fs::write(&output, generated).expect("write generated assurance catalogs");
}

fn load_catalog_sources(root: &Path) -> BTreeMap<&'static str, String> {
    let mut sources = BTreeMap::new();
    for (name, components) in CATALOGS {
        let relative = components.iter().collect::<PathBuf>();
        let path = root.join(&relative);
        println!("cargo:rerun-if-changed={}", path.display());
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()));
        assert!(
            source.ends_with('\n'),
            "{} must end with a newline",
            relative.display()
        );
        sources.insert(*name, source);
    }
    sources
}

fn obligation_ids(obligation_source: &str) -> BTreeSet<String> {
    let obligation_sections = parse_document(obligation_source);
    assert_eq!(
        obligation_sections.len(),
        1,
        "obligation catalog must be flat"
    );
    let obligation_values = &obligation_sections[0].values;
    expect_keys(
        obligation_values,
        &[
            "schema_version",
            "state",
            "pure_runtime",
            "effects",
            "concurrency",
            "presentation",
            "platform",
            "resource_behavior",
            "boundary_classes",
            "interaction_obligations",
            "generated_direct_claim_evidence",
        ],
        "obligation catalog",
    );
    require_unsigned(obligation_values, "schema_version", "obligation catalog", 2);
    assert_eq!(
        string(
            value(obligation_values, "state", "obligation catalog"),
            "state"
        ),
        "review-required",
        "obligation catalog must remain review-required"
    );
    assert!(
        !boolean(
            value(
                obligation_values,
                "generated_direct_claim_evidence",
                "obligation catalog"
            ),
            "generated_direct_claim_evidence"
        ),
        "generated descriptors cannot count as direct claim evidence"
    );
    [
        "pure_runtime",
        "effects",
        "concurrency",
        "presentation",
        "platform",
        "resource_behavior",
    ]
    .into_iter()
    .flat_map(|key| array(value(obligation_values, key, "obligation catalog"), key))
    .collect()
}

fn parse_claims(
    source: &str,
    normalizer_ids: &BTreeSet<&str>,
    obligation_ids: &BTreeSet<String>,
) -> Claims {
    try_parse_claims(source, normalizer_ids, obligation_ids)
        .unwrap_or_else(|error| panic!("{error}"))
}

#[allow(clippy::too_many_lines)]
fn try_parse_claims(
    source: &str,
    normalizer_ids: &BTreeSet<&str>,
    obligation_ids: &BTreeSet<String>,
) -> Result<Claims, String> {
    let sections = try_parse_document(source)?;
    if sections.len() < 2 {
        return Err("requirement catalog lacks default requirement".to_owned());
    }
    if !sections[0].header.is_empty() {
        return Err("claim catalog preamble is missing".to_owned());
    }
    try_expect_keys(
        &sections[0].values,
        &["schema_version", "baseline", "registry", "dimensions"],
        "requirement catalog preamble",
    )?;
    try_require_unsigned(
        &sections[0].values,
        "schema_version",
        "requirement catalog",
        3,
    )?;
    let baseline = try_string(
        try_value(&sections[0].values, "baseline", "requirement catalog")?,
        "baseline",
    )?;
    if try_string(
        try_value(&sections[0].values, "registry", "requirement catalog")?,
        "registry",
    )? != "compat/builtin-registry.json"
    {
        return Err("requirement catalog registry path differs".to_owned());
    }
    let catalog_dimensions = try_array(
        try_value(&sections[0].values, "dimensions", "requirement catalog")?,
        "dimensions",
    )?;
    if catalog_dimensions
        .iter()
        .map(String::as_str)
        .ne(dimensions().iter().copied())
    {
        return Err("requirement catalog dimension order differs".to_owned());
    }
    if sections[1].header != "default_requirement" {
        return Err(
            "requirement catalog must declare [default_requirement] before overrides".to_owned(),
        );
    }
    let default_scope = try_parse_claim_scope(
        &sections[1].values,
        "default scope",
        normalizer_ids,
        obligation_ids,
    )?;
    let mut overrides = Vec::new();
    let mut seen_cells = BTreeSet::new();
    let mut index = 2;
    while index < sections.len() {
        let claim = &sections[index];
        if claim.header != "overrides" {
            return Err("expected [[overrides]] section".to_owned());
        }
        try_expect_keys(
            &claim.values,
            &["builtin", "dimensions"],
            "requirement override",
        )?;
        let builtin = try_string(
            try_value(&claim.values, "builtin", "requirement override")?,
            "builtin",
        )?;
        if builtin.is_empty() {
            return Err("claim builtin must not be empty".to_owned());
        }
        let override_dimensions = try_array(
            try_value(&claim.values, "dimensions", "requirement override")?,
            "dimensions",
        )?;
        try_validate_unique_members(&override_dimensions, dimensions(), "requirement dimensions")?;
        index += 1;
        let mut scopes = Vec::new();
        while index < sections.len() && sections[index].header == "overrides.scopes" {
            scopes.push(try_parse_claim_scope(
                &sections[index].values,
                &format!("requirement scope {builtin}"),
                normalizer_ids,
                obligation_ids,
            )?);
            index += 1;
        }
        if scopes.is_empty() {
            return Err(format!("requirement {builtin} lacks a scope"));
        }
        for dimension in override_dimensions {
            if !seen_cells.insert((builtin.clone(), dimension.clone())) {
                return Err(format!("duplicate requirement cell {builtin}/{dimension}"));
            }
            try_validate_nonoverlapping_scopes(&scopes, &builtin, &dimension)?;
            overrides.push(ClaimOverride {
                builtin: builtin.clone(),
                dimension,
                scopes: scopes.clone(),
            });
        }
    }
    Ok(Claims {
        baseline,
        default_scope,
        overrides,
    })
}

fn try_parse_claim_scope(
    values: &BTreeMap<String, String>,
    context: &str,
    normalizer_ids: &BTreeSet<&str>,
    obligation_ids: &BTreeSet<String>,
) -> Result<ClaimScope, String> {
    try_expect_keys(values, REQUIREMENT_SCOPE_KEYS, context)?;
    let scope = ClaimScope {
        profiles: try_array(try_value(values, "profiles", context)?, "profiles")?,
        platforms: try_array(try_value(values, "platforms", context)?, "platforms")?,
        evidence_strategy: try_string(
            try_value(values, "evidence_strategy", context)?,
            "evidence_strategy",
        )?,
        evidence: try_array(try_value(values, "evidence", context)?, "evidence")?,
        normalizers: try_array(try_value(values, "normalizers", context)?, "normalizers")?,
        obligations: try_array(try_value(values, "obligations", context)?, "obligations")?,
        applicability_rule: try_string(
            try_value(values, "applicability_rule", context)?,
            "applicability_rule",
        )?,
        rationale: try_string(try_value(values, "rationale", context)?, "rationale")?,
        tracking_issue: try_string(
            try_value(values, "tracking_issue", context)?,
            "tracking_issue",
        )?,
        review_group: try_string(try_value(values, "review_group", context)?, "review_group")?,
    };
    if scope.profiles.is_empty() {
        return Err(format!("{context} has no profiles"));
    }
    if scope.platforms.is_empty() {
        return Err(format!("{context} has no platforms"));
    }
    try_validate_unique_members(&scope.profiles, profiles(), "claim profiles")?;
    try_validate_unique_members(
        &scope.platforms,
        requirement_platforms(),
        "requirement platforms",
    )?;
    if !evidence_strategies().contains(&scope.evidence_strategy.as_str()) {
        return Err(format!(
            "unknown requirement evidence strategy {:?}",
            scope.evidence_strategy
        ));
    }
    try_validate_unique(&scope.evidence, "claim evidence")?;
    try_validate_unique(&scope.normalizers, "claim normalizers")?;
    try_validate_unique(&scope.obligations, "claim obligations")?;
    if !scope
        .normalizers
        .iter()
        .all(|normalizer| normalizer_ids.contains(normalizer.as_str()))
    {
        return Err(format!("{context} names an unknown normalizer"));
    }
    if !scope
        .obligations
        .iter()
        .all(|obligation| obligation_ids.contains(obligation))
    {
        return Err(format!("{context} names an unknown obligation"));
    }
    if scope.applicability_rule.is_empty()
        || scope.rationale.is_empty()
        || scope.tracking_issue.is_empty()
        || scope.review_group.is_empty()
    {
        return Err(format!("{context} lacks required review metadata"));
    }
    Ok(scope)
}

fn try_validate_nonoverlapping_scopes(
    scopes: &[ClaimScope],
    builtin: &str,
    dimension: &str,
) -> Result<(), String> {
    for (index, scope) in scopes.iter().enumerate() {
        for other in &scopes[..index] {
            let profile_overlap = scope
                .profiles
                .iter()
                .any(|profile| other.profiles.contains(profile));
            let platform_overlap = scope
                .platforms
                .iter()
                .any(|platform| other.platforms.contains(platform));
            if profile_overlap && platform_overlap {
                return Err(format!("claim scopes overlap for {builtin}/{dimension}"));
            }
        }
    }
    Ok(())
}

#[allow(clippy::too_many_lines)]
fn parse_normalizers(source: &str, implementation_source: &[u8]) -> Vec<Normalizer> {
    try_parse_normalizers(source, implementation_source).unwrap_or_else(|error| panic!("{error}"))
}

#[allow(clippy::too_many_lines)]
fn try_parse_normalizers(
    source: &str,
    implementation_source: &[u8],
) -> Result<Vec<Normalizer>, String> {
    let sections = try_parse_document(source)?;
    let preamble = sections
        .first()
        .ok_or_else(|| "normalizer catalog is empty".to_owned())?;
    if !preamble.header.is_empty() {
        return Err("normalizer preamble is missing".to_owned());
    }
    try_expect_keys(
        &sections[0].values,
        &[
            "schema_version",
            "state",
            "typed_only",
            "require_idempotence",
            "require_protected_field_invariance",
            "require_shadow_diff",
            "require_mutation_suite",
            "exact_claims_allow_normalizers",
        ],
        "normalizer preamble",
    )?;
    try_require_unsigned(
        &sections[0].values,
        "schema_version",
        "normalizer catalog",
        1,
    )?;
    if try_string(
        try_value(&sections[0].values, "state", "normalizer catalog")?,
        "state",
    )? != "review-required"
    {
        return Err("normalizer catalog must remain review-required".to_owned());
    }
    for key in [
        "typed_only",
        "require_idempotence",
        "require_protected_field_invariance",
        "require_shadow_diff",
        "require_mutation_suite",
    ] {
        if !try_boolean(
            try_value(&sections[0].values, key, "normalizer catalog")?,
            key,
        )? {
            return Err(format!("normalizer catalog requires {key}"));
        }
    }
    if try_boolean(
        try_value(
            &sections[0].values,
            "exact_claims_allow_normalizers",
            "normalizer catalog",
        )?,
        "exact_claims_allow_normalizers",
    )? {
        return Err("exact claims cannot allow normalizers".to_owned());
    }
    let mut seen_ids = BTreeSet::new();
    let mut seen_variants = BTreeSet::new();
    let mut normalizers = Vec::new();
    for section in sections.iter().skip(1) {
        if section.header != "normalizer" {
            return Err("unknown normalizer section".to_owned());
        }
        try_expect_keys(&section.values, NORMALIZER_KEYS, "normalizer")?;
        let id = try_string(
            try_value(&section.values, "id", "normalizer")?,
            "normalizer id",
        )?;
        let variant = try_string(
            try_value(&section.values, "variant", "normalizer")?,
            "normalizer variant",
        )?;
        if !valid_kebab_identifier(&id) {
            return Err(format!("invalid normalizer id {id:?}"));
        }
        if !valid_rust_variant(&variant) {
            return Err(format!("invalid normalizer variant {variant:?}"));
        }
        if !seen_ids.insert(id.clone()) {
            return Err(format!("duplicate normalizer id {id}"));
        }
        if !seen_variants.insert(variant.clone()) {
            return Err(format!("duplicate normalizer variant {variant}"));
        }
        let implementation = try_string(
            try_value(&section.values, "implementation", "normalizer")?,
            "normalizer implementation",
        )?;
        if !valid_snake_identifier(&implementation) {
            return Err(format!(
                "invalid normalizer implementation {implementation:?}"
            ));
        }
        let implementation_marker = format!("fn {implementation}(");
        if !implementation_source
            .windows(implementation_marker.len())
            .any(|window| window == implementation_marker.as_bytes())
        {
            return Err(format!(
                "normalizer implementation {implementation:?} is absent from typed normalizer source"
            ));
        }
        let version = try_unsigned(
            try_value(&section.values, "version", "normalizer")?,
            "version",
        )?;
        if version == 0 {
            return Err("normalizer version must be positive".to_owned());
        }
        let allowed_dimensions = try_array(
            try_value(&section.values, "allowed_dimensions", "normalizer")?,
            "allowed_dimensions",
        )?;
        try_validate_unique_members(
            &allowed_dimensions,
            dimensions(),
            "normalizer allowed dimensions",
        )?;
        if allowed_dimensions.is_empty() {
            return Err("normalizer must allow at least one typed dimension".to_owned());
        }
        let allowed_fields = try_array(
            try_value(&section.values, "allowed_fields", "normalizer")?,
            "allowed_fields",
        )?;
        let forbidden_fields = try_array(
            try_value(&section.values, "forbidden_fields", "normalizer")?,
            "forbidden_fields",
        )?;
        try_validate_unique_members(&allowed_fields, observation_fields(), "allowed fields")?;
        try_validate_unique_members(&forbidden_fields, observation_fields(), "forbidden fields")?;
        if allowed_fields.is_empty() || forbidden_fields.is_empty() {
            return Err("normalizer field scopes must be explicit".to_owned());
        }
        if allowed_fields
            .iter()
            .any(|field| forbidden_fields.contains(field))
        {
            return Err("normalizer allowed and forbidden fields overlap".to_owned());
        }
        if !try_boolean(
            try_value(&section.values, "idempotent", "normalizer")?,
            "idempotent",
        )? {
            return Err("normalizer must be idempotent".to_owned());
        }
        let requires_platforms = try_array(
            try_value(&section.values, "requires_platforms", "normalizer")?,
            "requires_platforms",
        )?;
        try_validate_unique_members(
            &requires_platforms,
            platforms(),
            "normalizer required platforms",
        )?;
        if requires_platforms != platforms() {
            return Err("normalizer certification must cover every native platform".to_owned());
        }
        let mutation_suite = try_string(
            try_value(&section.values, "mutation_suite", "normalizer")?,
            "mutation_suite",
        )?;
        if !valid_kebab_identifier(&mutation_suite) {
            return Err(format!("invalid mutation suite {mutation_suite:?}"));
        }
        let max_changed_values = try_unsigned(
            try_value(&section.values, "max_changed_values", "normalizer")?,
            "max_changed_values",
        )?;
        if max_changed_values == 0 {
            return Err("normalizer changed-value budget must be positive".to_owned());
        }
        let mut hasher = digest::Sha256::new();
        hasher.update(implementation.as_bytes());
        hasher.update(&[0]);
        hasher.update(implementation_source);
        normalizers.push(Normalizer {
            id,
            variant,
            implementation,
            version,
            allowed_dimensions,
            allowed_fields,
            forbidden_fields,
            idempotent: true,
            max_changed_values,
            max_removed_bytes: try_unsigned(
                try_value(&section.values, "max_removed_bytes", "normalizer")?,
                "max_removed_bytes",
            )?,
            requires_platforms,
            mutation_suite,
            implementation_sha256: hasher.finish().hex(),
        });
    }
    Ok(normalizers)
}

fn validate_flat_catalogs(sources: &BTreeMap<&str, String>) {
    try_validate_flat_catalogs(sources).unwrap_or_else(|error| panic!("{error}"));
}

#[allow(clippy::too_many_lines)]
fn try_validate_flat_catalogs(sources: &BTreeMap<&str, String>) -> Result<(), String> {
    let claim_rules = sources
        .get("CLAIM_RULES")
        .ok_or_else(|| "claim rules source is missing".to_owned())?;
    let rules = try_parse_document(claim_rules)?;
    if rules.len() != 1 {
        return Err("claim rules must be flat".to_owned());
    }
    try_expect_keys(
        &rules[0].values,
        &[
            "schema_version",
            "default_decision",
            "automatic_not_applicable",
            "unknown_builtin_family",
            "unknown_dimension",
        ],
        "claim rules",
    )?;
    try_require_unsigned(&rules[0].values, "schema_version", "claim rules", 3)?;
    if try_string(
        try_value(&rules[0].values, "default_decision", "claim rules")?,
        "default_decision",
    )? != "applicable-review-required"
        || try_string(
            try_value(&rules[0].values, "unknown_builtin_family", "claim rules")?,
            "unknown_builtin_family",
        )? != "applicable-review-required"
        || try_string(
            try_value(&rules[0].values, "unknown_dimension", "claim rules")?,
            "unknown_dimension",
        )? != "reject"
    {
        return Err("claim rules do not use the exact fail-closed decisions".to_owned());
    }
    if try_boolean(
        try_value(&rules[0].values, "automatic_not_applicable", "claim rules")?,
        "automatic_not_applicable",
    )? {
        return Err(
            "claim rules must fail closed instead of automatically marking cells not applicable"
                .to_owned(),
        );
    }
    let divergence_source = sources
        .get("DIVERGENCE_CATALOG")
        .ok_or_else(|| "divergence catalog source is missing".to_owned())?;
    let divergence = try_parse_document(divergence_source)?;
    if divergence.len() != 1 {
        return Err("divergence catalog must be flat".to_owned());
    }
    try_expect_keys(
        &divergence[0].values,
        &[
            "schema_version",
            "baseline",
            "state",
            "require_exact_scope",
            "require_mismatch_fingerprint",
            "require_expiry",
            "require_impact_approvals",
            "allow_wildcards",
        ],
        "divergence catalog",
    )?;
    try_require_unsigned(
        &divergence[0].values,
        "schema_version",
        "divergence catalog",
        2,
    )?;
    if try_string(
        try_value(&divergence[0].values, "baseline", "divergence catalog")?,
        "baseline",
    )? != "2026-05-29"
    {
        return Err("divergence baseline is not accepted".to_owned());
    }
    if try_string(
        try_value(&divergence[0].values, "state", "divergence catalog")?,
        "state",
    )? != "none-accepted"
    {
        return Err("divergence catalog must fail closed".to_owned());
    }
    for key in [
        "require_exact_scope",
        "require_mismatch_fingerprint",
        "require_expiry",
        "require_impact_approvals",
    ] {
        if !try_boolean(
            try_value(&divergence[0].values, key, "divergence catalog")?,
            key,
        )? {
            return Err(format!("divergence catalog requires {key}"));
        }
    }
    if try_boolean(
        try_value(
            &divergence[0].values,
            "allow_wildcards",
            "divergence catalog",
        )?,
        "allow_wildcards",
    )? {
        return Err("divergence catalog cannot allow wildcards".to_owned());
    }
    Ok(())
}

/// Panic-free admission seam for fuzzing the exact build-time catalogs.
///
/// This deliberately invokes the same parsers and schema checks as `main`.
/// It is not used to relax build failures: production catalog generation still
/// treats every malformed record as a hard build error.
///
/// # Errors
///
/// Returns an error when the input is noncanonical, the target kind is unknown,
/// or the exact production parser or schema validator rejects the catalog.
///
pub fn fuzz_validate_catalog(kind: &str, source: &str) -> Result<(), String> {
    if !source.ends_with('\n') || source.contains('\0') {
        return Err("catalog is not canonical newline-terminated text".to_owned());
    }
    match kind {
        "requirement" => {
            let implementation = include_bytes!("../hell-testkit/src/lib.rs");
            let normalizers = parse_normalizers(
                include_str!("../../compat/normalizers.toml"),
                implementation,
            );
            let normalizer_ids = normalizers
                .iter()
                .map(|normalizer| normalizer.id.as_str())
                .collect::<BTreeSet<_>>();
            let obligations = obligation_ids(include_str!("../../compat/corpus-obligations.toml"));
            let _ = try_parse_claims(source, &normalizer_ids, &obligations)?;
            Ok(())
        }
        "normalizer" => {
            let _ = try_parse_normalizers(source, include_bytes!("../hell-testkit/src/lib.rs"))?;
            Ok(())
        }
        "divergence" => {
            let sources = BTreeMap::from([
                (
                    "CLAIM_RULES",
                    include_str!("../../compat/claim-rules.toml").to_owned(),
                ),
                ("DIVERGENCE_CATALOG", source.to_owned()),
            ]);
            try_validate_flat_catalogs(&sources)
        }
        _ => Err(format!("unknown catalog fuzz target {kind:?}")),
    }
}

fn emit_claims(generated: &mut String, claims: &Claims) {
    writeln!(
        generated,
        "pub const REQUIREMENT_BASELINE: &str = {:?};",
        claims.baseline
    )
    .expect("write claim baseline");
    generated.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    generated.push_str("pub struct GeneratedRequirementScope { pub profiles: &'static [&'static str], pub platforms: &'static [&'static str], pub evidence_strategy: &'static str, pub evidence: &'static [&'static str], pub normalizers: &'static [&'static str], pub obligations: &'static [&'static str], pub applicability_rule: &'static str, pub rationale: &'static str, pub tracking_issue: &'static str, pub review_group: &'static str }\n");
    generated.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    generated.push_str("pub struct GeneratedRequirement { pub builtin: &'static str, pub dimension: &'static str, pub scopes: &'static [GeneratedRequirementScope] }\n");
    generated.push_str("pub const DEFAULT_REQUIREMENT_SCOPE: GeneratedRequirementScope = ");
    emit_scope(generated, &claims.default_scope);
    generated.push_str(";\n");
    generated.push_str("pub const REQUIREMENT_OVERRIDES: &[GeneratedRequirement] = &[\n");
    for claim in &claims.overrides {
        write!(
            generated,
            "GeneratedRequirement {{ builtin: {:?}, dimension: {:?}, scopes: &[",
            claim.builtin, claim.dimension
        )
        .expect("write claim override");
        for scope in &claim.scopes {
            emit_scope(generated, scope);
            generated.push(',');
        }
        generated.push_str("] },\n");
    }
    generated.push_str("];\n");
}

fn emit_scope(generated: &mut String, scope: &ClaimScope) {
    generated.push_str("GeneratedRequirementScope {");
    emit_string_slice_field(generated, "profiles", &scope.profiles);
    emit_string_slice_field(generated, "platforms", &scope.platforms);
    write!(
        generated,
        "evidence_strategy: {:?},",
        scope.evidence_strategy
    )
    .expect("write evidence strategy");
    emit_string_slice_field(generated, "evidence", &scope.evidence);
    emit_string_slice_field(generated, "normalizers", &scope.normalizers);
    emit_string_slice_field(generated, "obligations", &scope.obligations);
    write!(
        generated,
        "applicability_rule: {:?},rationale: {:?},tracking_issue: {:?},review_group: {:?}",
        scope.applicability_rule, scope.rationale, scope.tracking_issue, scope.review_group
    )
    .expect("write scope metadata");
    generated.push('}');
}

fn emit_normalizers(generated: &mut String, normalizers: &[Normalizer]) {
    generated
        .push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\npub enum NormalizerId {");
    for normalizer in normalizers {
        write!(generated, "{},", normalizer.variant).expect("write normalizer variant");
    }
    generated.push_str("}\nimpl NormalizerId { pub const ALL: &'static [Self] = &[");
    for normalizer in normalizers {
        write!(generated, "Self::{},", normalizer.variant).expect("write normalizer list");
    }
    generated.push_str("]; #[must_use] pub const fn as_str(self) -> &'static str { match self {");
    for normalizer in normalizers {
        write!(
            generated,
            "Self::{} => {:?},",
            normalizer.variant, normalizer.id
        )
        .expect("write normalizer names");
    }
    generated.push_str("} } }\n");
    generated.push_str(
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\npub enum ObservationField {",
    );
    for (_, variant) in observation_field_variants() {
        write!(generated, "{variant},").expect("write observation field variant");
    }
    generated.push_str("}\nimpl ObservationField { #[must_use] pub const fn as_str(self) -> &'static str { match self {");
    for (field, variant) in observation_field_variants() {
        write!(generated, "Self::{variant} => {field:?},").expect("write observation field name");
    }
    generated.push_str("} } }\n");
    generated.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct NormalizerContract { pub id: NormalizerId, pub implementation: &'static str, pub implementation_sha256: &'static str, pub version: u64, pub allowed_dimensions: &'static [super::CompatibilityDimension], pub allowed_fields: &'static [ObservationField], pub forbidden_fields: &'static [ObservationField], pub idempotent: bool, pub max_changed_values: u64, pub max_removed_bytes: u64, pub requires_platforms: &'static [super::ClaimPlatform], pub mutation_suite: &'static str }\n");
    generated.push_str("pub const NORMALIZER_CONTRACTS: &[NormalizerContract] = &[\n");
    for normalizer in normalizers {
        write!(
            generated,
            "NormalizerContract {{ id: NormalizerId::{}, implementation: {:?}, implementation_sha256: {:?}, version: {}, allowed_dimensions: &[",
            normalizer.variant,
            normalizer.implementation,
            normalizer.implementation_sha256,
            normalizer.version
        )
        .expect("write normalizer contract");
        for dimension in &normalizer.allowed_dimensions {
            write!(
                generated,
                "super::CompatibilityDimension::{},",
                dimension_variant(dimension)
            )
            .expect("write normalizer dimension");
        }
        generated.push_str("], allowed_fields: &[");
        for field in &normalizer.allowed_fields {
            write!(
                generated,
                "ObservationField::{},",
                observation_field_variant(field)
            )
            .expect("write allowed field");
        }
        generated.push_str("], forbidden_fields: &[");
        for field in &normalizer.forbidden_fields {
            write!(
                generated,
                "ObservationField::{},",
                observation_field_variant(field)
            )
            .expect("write forbidden field");
        }
        write!(
            generated,
            "], idempotent: {}, max_changed_values: {}, max_removed_bytes: {}, requires_platforms: &[",
            normalizer.idempotent, normalizer.max_changed_values, normalizer.max_removed_bytes
        )
        .expect("write normalizer limits");
        for platform in &normalizer.requires_platforms {
            write!(
                generated,
                "super::ClaimPlatform::{},",
                platform_variant(platform)
            )
            .expect("write required platform");
        }
        writeln!(
            generated,
            "], mutation_suite: {:?} }},",
            normalizer.mutation_suite
        )
        .expect("write mutation suite");
    }
    generated.push_str("];\n");
}

fn emit_flat_constants(generated: &mut String, sources: &BTreeMap<&str, String>) {
    let rules = parse_document(sources.get("CLAIM_RULES").expect("claim rules source"));
    let rules = &rules[0].values;
    for (constant, key) in [
        ("DEFAULT_APPLICABILITY_DECISION", "default_decision"),
        ("UNKNOWN_BUILTIN_DECISION", "unknown_builtin_family"),
        ("UNKNOWN_DIMENSION_DECISION", "unknown_dimension"),
    ] {
        writeln!(
            generated,
            "pub const {constant}: &str = {:?};",
            string(value(rules, key, "claim rules"), key)
        )
        .expect("write applicability constant");
    }
    writeln!(
        generated,
        "pub const AUTOMATIC_NOT_APPLICABLE: bool = {};",
        boolean(
            value(rules, "automatic_not_applicable", "claim rules"),
            "automatic_not_applicable"
        )
    )
    .expect("write automatic applicability policy");
    let obligations = parse_document(
        sources
            .get("OBLIGATION_CATALOG")
            .expect("obligation catalog source"),
    );
    let obligations = &obligations[0].values;
    writeln!(
        generated,
        "pub const GENERATED_DIRECT_CLAIM_EVIDENCE: bool = {};",
        boolean(
            value(
                obligations,
                "generated_direct_claim_evidence",
                "obligation catalog"
            ),
            "generated_direct_claim_evidence"
        )
    )
    .expect("write generated evidence policy");
    for (constant, key) in [
        ("PURE_RUNTIME_OBLIGATIONS", "pure_runtime"),
        ("EFFECT_OBLIGATIONS", "effects"),
        ("CONCURRENCY_OBLIGATIONS", "concurrency"),
        ("PRESENTATION_OBLIGATIONS", "presentation"),
        ("PLATFORM_OBLIGATIONS", "platform"),
        ("RESOURCE_OBLIGATIONS", "resource_behavior"),
        ("BOUNDARY_CLASSES", "boundary_classes"),
        ("INTERACTION_OBLIGATIONS", "interaction_obligations"),
    ] {
        let values = array(value(obligations, key, "obligation catalog"), key);
        write!(generated, "pub const {constant}: &[&str] = &[").expect("write obligation array");
        for item in values {
            write!(generated, "{item:?},").expect("write obligation item");
        }
        generated.push_str("];\n");
    }
    let divergence = parse_document(
        sources
            .get("DIVERGENCE_CATALOG")
            .expect("divergence catalog source"),
    );
    let divergence = &divergence[0].values;
    for (constant, key) in [
        ("DIVERGENCE_REQUIRE_EXACT_SCOPE", "require_exact_scope"),
        (
            "DIVERGENCE_REQUIRE_MISMATCH_FINGERPRINT",
            "require_mismatch_fingerprint",
        ),
        ("DIVERGENCE_REQUIRE_EXPIRY", "require_expiry"),
        (
            "DIVERGENCE_REQUIRE_IMPACT_APPROVALS",
            "require_impact_approvals",
        ),
        ("DIVERGENCE_ALLOW_WILDCARDS", "allow_wildcards"),
    ] {
        writeln!(
            generated,
            "pub const {constant}: bool = {};",
            boolean(value(divergence, key, "divergence catalog"), key)
        )
        .expect("write divergence policy constant");
    }
}

fn parse_document(source: &str) -> Vec<Section> {
    try_parse_document(source).unwrap_or_else(|error| panic!("{error}"))
}

fn try_parse_document(source: &str) -> Result<Vec<Section>, String> {
    let mut sections = vec![Section {
        header: String::new(),
        values: BTreeMap::new(),
    }];
    let mut pending_array = None::<(String, String, usize)>;
    for (line_index, raw) in source.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((_key, value, start)) = pending_array.as_mut() {
            if line.starts_with('[') {
                return Err(format!("table inside array starting at line {start}"));
            }
            value.push(' ');
            value.push_str(line);
            if line.ends_with(']') {
                let (key, value, _) = pending_array.take().expect("pending array exists");
                let prior = sections
                    .last_mut()
                    .ok_or_else(|| "document has no preamble".to_owned())?
                    .values
                    .insert(key.clone(), value);
                if prior.is_some() {
                    return Err(format!("duplicate key {key}"));
                }
            }
            continue;
        }
        if let Some(header) = line
            .strip_prefix("[[")
            .and_then(|line| line.strip_suffix("]]"))
        {
            if header.is_empty() {
                return Err(format!("empty array table at line {}", line_index + 1));
            }
            sections.push(Section {
                header: header.to_owned(),
                values: BTreeMap::new(),
            });
            continue;
        }
        if let Some(header) = line
            .strip_prefix('[')
            .and_then(|line| line.strip_suffix(']'))
        {
            if header.is_empty() {
                return Err(format!("empty table at line {}", line_index + 1));
            }
            sections.push(Section {
                header: header.to_owned(),
                values: BTreeMap::new(),
            });
            continue;
        }
        let (key, raw_value) = line
            .split_once('=')
            .ok_or_else(|| format!("catalog line {} is not an assignment", line_index + 1))?;
        let key = key.trim();
        let raw_value = raw_value.trim();
        if !valid_snake_identifier(key) {
            return Err(format!("invalid key {key:?}"));
        }
        if raw_value.is_empty() {
            return Err(format!("empty value for {key}"));
        }
        if raw_value.starts_with('[') && !raw_value.ends_with(']') {
            pending_array = Some((key.to_owned(), raw_value.to_owned(), line_index + 1));
            continue;
        }
        let prior = sections
            .last_mut()
            .ok_or_else(|| "document has no preamble".to_owned())?
            .values
            .insert(key.to_owned(), raw_value.to_owned());
        if prior.is_some() {
            return Err(format!("duplicate key {key}"));
        }
    }
    if let Some((key, _, start)) = pending_array {
        return Err(format!("unterminated array {key} starting at line {start}"));
    }
    Ok(sections)
}

fn try_expect_keys(
    values: &BTreeMap<String, String>,
    expected: &[&str],
    context: &str,
) -> Result<(), String> {
    let observed = values.keys().map(String::as_str).collect::<BTreeSet<_>>();
    let expected = expected.iter().copied().collect::<BTreeSet<_>>();
    (observed == expected)
        .then_some(())
        .ok_or_else(|| format!("{context} keys do not match schema"))
}

fn try_value<'a>(
    values: &'a BTreeMap<String, String>,
    key: &str,
    context: &str,
) -> Result<&'a str, String> {
    values
        .get(key)
        .map(String::as_str)
        .ok_or_else(|| format!("{context} lacks {key}"))
}

fn try_string(value: &str, key: &str) -> Result<String, String> {
    value
        .strip_prefix('"')
        .and_then(|value| value.strip_suffix('"'))
        .filter(|value| !value.contains('"') && !value.contains('\\'))
        .map(str::to_owned)
        .ok_or_else(|| format!("{key} must be a simple quoted string"))
}

fn try_array(value: &str, key: &str) -> Result<Vec<String>, String> {
    let inner = value
        .strip_prefix('[')
        .and_then(|value| value.strip_suffix(']'))
        .ok_or_else(|| format!("{key} must be a single-line array"))?;
    let inner = inner
        .trim()
        .strip_suffix(',')
        .unwrap_or(inner.trim())
        .trim();
    if inner.is_empty() {
        return Ok(Vec::new());
    }
    inner
        .split(',')
        .map(str::trim)
        .map(|value| try_string(value, key))
        .collect()
}

fn try_unsigned(value: &str, key: &str) -> Result<u64, String> {
    if value.starts_with('+') || (value != "0" && value.starts_with('0')) {
        return Err(format!("{key} is not a canonical unsigned integer"));
    }
    value
        .parse()
        .map_err(|_| format!("{key} is not an unsigned integer"))
}

fn try_require_unsigned(
    values: &BTreeMap<String, String>,
    key: &str,
    context: &str,
    expected: u64,
) -> Result<(), String> {
    (try_unsigned(try_value(values, key, context)?, key)? == expected)
        .then_some(())
        .ok_or_else(|| format!("{context} has the wrong {key}"))
}

fn try_boolean(value: &str, key: &str) -> Result<bool, String> {
    match value {
        "true" => Ok(true),
        "false" => Ok(false),
        _ => Err(format!("{key} is not a boolean")),
    }
}

fn try_validate_unique_members(
    values: &[String],
    allowed: &[&str],
    context: &str,
) -> Result<(), String> {
    try_validate_unique(values, context)?;
    for value in values {
        if !allowed.contains(&value.as_str()) {
            return Err(format!("unknown {context} {value:?}"));
        }
    }
    Ok(())
}

fn try_validate_unique(values: &[String], context: &str) -> Result<(), String> {
    let unique = values.iter().collect::<BTreeSet<_>>();
    (unique.len() == values.len())
        .then_some(())
        .ok_or_else(|| format!("duplicate {context}"))
}

fn expect_keys(values: &BTreeMap<String, String>, expected: &[&str], context: &str) {
    let observed = values.keys().map(String::as_str).collect::<BTreeSet<_>>();
    let expected = expected.iter().copied().collect::<BTreeSet<_>>();
    assert_eq!(observed, expected, "{context} keys do not match schema");
}

fn value<'a>(values: &'a BTreeMap<String, String>, key: &str, context: &str) -> &'a str {
    values
        .get(key)
        .map_or_else(|| panic!("{context} lacks {key}"), String::as_str)
}

fn string(value: &str, key: &str) -> String {
    value
        .strip_prefix('"')
        .and_then(|value| value.strip_suffix('"'))
        .filter(|value| !value.contains('"') && !value.contains('\\'))
        .map_or_else(
            || panic!("{key} must be a simple quoted string"),
            str::to_owned,
        )
}

fn array(value: &str, key: &str) -> Vec<String> {
    let inner = value
        .strip_prefix('[')
        .and_then(|value| value.strip_suffix(']'))
        .unwrap_or_else(|| panic!("{key} must be a single-line array"));
    if inner.trim().is_empty() {
        return Vec::new();
    }
    inner
        .split(',')
        .map(str::trim)
        .map(|value| string(value, key))
        .collect()
}

fn unsigned(value: &str, key: &str) -> u64 {
    assert!(
        !value.starts_with('+') && (value == "0" || !value.starts_with('0')),
        "{key} is not a canonical unsigned integer"
    );
    value
        .parse()
        .unwrap_or_else(|_| panic!("{key} is not an unsigned integer"))
}

fn require_unsigned(values: &BTreeMap<String, String>, key: &str, context: &str, expected: u64) {
    assert_eq!(
        unsigned(value(values, key, context), key),
        expected,
        "{context} has the wrong {key}"
    );
}

fn boolean(value: &str, key: &str) -> bool {
    match value {
        "true" => true,
        "false" => false,
        _ => panic!("{key} is not a boolean"),
    }
}

fn valid_snake_identifier(value: &str) -> bool {
    let mut bytes = value.bytes();
    bytes.next().is_some_and(|byte| byte.is_ascii_lowercase())
        && bytes.all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
}

fn valid_kebab_identifier(value: &str) -> bool {
    let mut bytes = value.bytes();
    bytes.next().is_some_and(|byte| byte.is_ascii_lowercase())
        && bytes.all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
}

fn valid_rust_variant(value: &str) -> bool {
    let mut bytes = value.bytes();
    bytes.next().is_some_and(|byte| byte.is_ascii_uppercase())
        && bytes.all(|byte| byte.is_ascii_alphanumeric())
}

fn profiles() -> &'static [&'static str] {
    &["upstream", "sandboxed"]
}

fn platforms() -> &'static [&'static str] {
    &["linux", "macos", "windows"]
}

fn requirement_platforms() -> &'static [&'static str] {
    &["linux-x86_64", "macos-aarch64", "windows-x86_64"]
}

fn dimensions() -> &'static [&'static str] {
    &[
        "parse",
        "static-semantics",
        "pure-runtime",
        "effects",
        "concurrency",
        "presentation",
        "platform",
        "resource-behavior",
    ]
}

fn evidence_strategies() -> &'static [&'static str] {
    &[
        "native-oracle",
        "portable-static",
        "structural-invariant",
        "committed-differential-corpus",
        "cross-platform-relation",
    ]
}

fn observation_fields() -> &'static [&'static str] {
    &[
        "diagnostic.paths[*]",
        "stderr.path_tokens[*]",
        "stdout",
        "diagnostic.code",
        "diagnostic.line",
        "diagnostic.column",
        "filesystem",
        "resourceAudit",
        "status",
        "semanticTrace",
        "taskEvents",
    ]
}

fn observation_field_variants() -> &'static [(&'static str, &'static str)] {
    &[
        ("diagnostic.paths[*]", "DiagnosticPaths"),
        ("stderr.path_tokens[*]", "StderrPathTokens"),
        ("stdout", "Stdout"),
        ("diagnostic.code", "DiagnosticCode"),
        ("diagnostic.line", "DiagnosticLine"),
        ("diagnostic.column", "DiagnosticColumn"),
        ("filesystem", "Filesystem"),
        ("resourceAudit", "ResourceAudit"),
        ("status", "Status"),
        ("semanticTrace", "SemanticTrace"),
        ("taskEvents", "TaskEvents"),
    ]
}

fn observation_field_variant(field: &str) -> &'static str {
    observation_field_variants()
        .iter()
        .find_map(|(name, variant)| (*name == field).then_some(*variant))
        .expect("field was validated")
}

fn dimension_variant(dimension: &str) -> &'static str {
    match dimension {
        "parse" => "Parse",
        "static-semantics" => "StaticSemantics",
        "pure-runtime" => "PureRuntime",
        "effects" => "Effects",
        "concurrency" => "Concurrency",
        "presentation" => "Presentation",
        "platform" => "Platform",
        "resource-behavior" => "ResourceBehavior",
        _ => panic!("dimension was not validated"),
    }
}

fn platform_variant(platform: &str) -> &'static str {
    match platform {
        "linux" => "Linux",
        "macos" => "MacOs",
        "windows" => "Windows",
        _ => panic!("platform was not validated"),
    }
}

fn emit_string_slice_field(generated: &mut String, field: &str, values: &[String]) {
    write!(generated, "{field}: &[").expect("write slice field");
    for value in values {
        write!(generated, "{value:?},").expect("write slice value");
    }
    generated.push_str("],");
}
