[package]
name = "hell-http-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes = { version = "=1.12.1", default-features = false, features = ["std"] }
hyper = { version = "=1.11.0", default-features = false, features = ["http1", "server"] }
hyper-util = { version = "=0.1.20", default-features = false, features = ["tokio"] }
tokio = { version = "=1.53.1", default-features = false, features = ["net", "rt-multi-thread", "sync", "time"] }

[lints]
workspace = true
