[package]
name = "hell-testkit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hell-platform = { version = "0.1.0", path = "../hell-platform" }

[dev-dependencies]
hell-compiler = { version = "0.1.0", path = "../hell-compiler" }
hell-source = { version = "0.1.0", path = "../hell-source" }
hell-syntax = { version = "0.1.0", path = "../hell-syntax" }

[lints]
workspace = true
