[package]
name = "hell-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hell-builtins = { version = "0.1.0", path = "../hell-builtins" }
hell-source = { version = "0.1.0", path = "../hell-source" }
hell-types = { version = "0.1.0", path = "../hell-types" }

[lints]
workspace = true
