[package]
name = "hell-ci"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
mutation-testing = []

[[bin]]
name = "hell-ci"
path = "src/main.rs"

[dependencies]
flate2 = { version = "1.1.2", default-features = false, features = ["rust_backend"] }
hell-builtins = { version = "0.1.0", path = "../hell-builtins" }
hell-compiler = { version = "0.1.0", path = "../hell-compiler" }
hell-docgen = { version = "0.1.0", path = "../hell-docgen" }
hell-runtime = { version = "0.1.0", path = "../hell-runtime" }
hell-source = { version = "0.1.0", path = "../hell-source" }
hell-syntax = { version = "0.1.0", path = "../hell-syntax" }
hell-testkit = { version = "0.1.0", path = "../hell-testkit" }
tar = "0.4.44"

[lints]
workspace = true
