use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use serde_yaml::{Mapping, Value};

use super::model::{Access, Credential, Manifest, MergeGroup, Operation, Permission, Workflow};
use super::validate::Diagnostic;
use crate::release::manifest::write_atomic;

pub(super) fn workflows(
    manifest: &Manifest,
    _repository_root: &Path,
    output: &Path,
) -> Result<(), Diagnostic> {
    let metadata = fs::symlink_metadata(output);
    match metadata {
        Ok(metadata) if metadata.is_dir() && !metadata.file_type().is_symlink() => {
            let observed = fs::read_dir(output)
                .map_err(|error| {
                    Diagnostic::manifest(format!("cannot read {}: {error}", output.display()))
                })?
                .map(|entry| {
                    entry.map(|entry| entry.file_name()).map_err(|error| {
                        Diagnostic::manifest(format!("cannot read workflow output entry: {error}"))
                    })
                })
                .collect::<Result<BTreeSet<_>, _>>()?;
            let expected = manifest
                .workflows
                .values()
                .map(|workflow| {
                    workflow
                        .path
                        .file_name()
                        .expect("validated path")
                        .to_owned()
                })
                .collect::<BTreeSet<_>>();
            if !observed.is_empty() && observed != expected {
                return Err(Diagnostic::manifest(format!(
                    "workflow output inventory differs: expected {expected:?}, observed {observed:?}"
                )));
            }
        }
        Ok(_) => {
            return Err(Diagnostic::manifest(format!(
                "{} is not a regular directory",
                output.display()
            )));
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => fs::create_dir_all(output)
            .map_err(|error| {
                Diagnostic::manifest(format!("cannot create {}: {error}", output.display()))
            })?,
        Err(error) => {
            return Err(Diagnostic::manifest(format!(
                "cannot inspect {}: {error}",
                output.display()
            )));
        }
    }
    for workflow in manifest.workflows.values() {
        let name = workflow.path.file_name().expect("validated workflow path");
        let bytes = workflow_bytes(manifest, workflow)?;
        write_atomic(&output.join(name), &bytes).map_err(Diagnostic::manifest)?;
    }
    Ok(())
}

pub(super) fn workflow_bytes(
    manifest: &Manifest,
    workflow: &Workflow,
) -> Result<Vec<u8>, Diagnostic> {
    let document = workflow_value(manifest, workflow);
    let yaml = serde_yaml::to_string(&document).map_err(|error| {
        Diagnostic::manifest(format!(
            "cannot serialize workflow {}: {error}",
            workflow.id
        ))
    })?;
    let yaml = indent_block_sequences(&yaml);
    let mut output = format!(
        "# Generated by `hell-ci protocol render`.\n# Source: ci/protocol/v1.toml\n# Protocol SHA-256: {}\n# Edit the protocol manifest or generator, not this file.\n{yaml}",
        manifest.sha256
    ).into_bytes();
    if !output.ends_with(b"\n") {
        output.push(b'\n');
    }
    Ok(output)
}

fn indent_block_sequences(document: &str) -> String {
    let mut output = String::with_capacity(document.len());
    let mut sequence_indents = Vec::new();
    let mut block_scalar_indent = None;

    for line in document.split_inclusive('\n') {
        let content = line.strip_suffix('\n').unwrap_or(line);
        let indent = content.bytes().take_while(|byte| *byte == b' ').count();

        if let Some(scalar_indent) = block_scalar_indent {
            if content.trim().is_empty() || indent > scalar_indent {
                push_indented_line(&mut output, line, sequence_indents.len());
                continue;
            }
            block_scalar_indent = None;
        }

        let trimmed = &content[indent..];
        let sequence_item = trimmed == "-" || trimmed.starts_with("- ");
        while sequence_indents.last().is_some_and(|sequence_indent| {
            indent < *sequence_indent || (indent == *sequence_indent && !sequence_item)
        }) {
            sequence_indents.pop();
        }
        if sequence_item && sequence_indents.last().copied() != Some(indent) {
            sequence_indents.push(indent);
        }

        push_indented_line(&mut output, line, sequence_indents.len());
        if block_scalar_indicator(trimmed).is_some() {
            block_scalar_indent = Some(indent);
        }
    }

    output
}

fn push_indented_line(output: &mut String, line: &str, sequence_depth: usize) {
    for _ in 0..sequence_depth {
        output.push_str("  ");
    }
    output.push_str(line);
}

fn block_scalar_indicator(line: &str) -> Option<&str> {
    let indicator = line
        .rsplit_once(':')
        .map(|(_, value)| value.trim())
        .or_else(|| line.strip_prefix("- ").map(str::trim))?;
    (indicator.starts_with('|') || indicator.starts_with('>')).then_some(indicator)
}

fn workflow_value(manifest: &Manifest, workflow: &Workflow) -> Value {
    let mut root = Mapping::new();
    insert(&mut root, "name", string(&workflow.name));
    if let Some(run_name) = &workflow.physical.run_name {
        insert(&mut root, "run-name", string(run_name));
    }
    insert(&mut root, "on", trigger(manifest, workflow));
    let workflow_permission = manifest
        .permissions
        .get(&workflow.physical.permission)
        .expect("permission reference checked");
    insert(&mut root, "permissions", permission(workflow_permission));
    insert(&mut root, "concurrency", concurrency(workflow));
    insert(
        &mut root,
        "jobs",
        jobs(manifest, workflow, workflow_permission),
    );
    Value::Mapping(root)
}

fn trigger(manifest: &Manifest, workflow: &Workflow) -> Value {
    let mut trigger = Mapping::new();
    if workflow.trigger.push.branches {
        let mut push = Mapping::new();
        insert(&mut push, "branches", Value::Sequence(vec![string("**")]));
        if workflow.trigger.push.tags {
            insert(&mut push, "tags", Value::Sequence(vec![string("**")]));
        } else {
            insert(
                &mut push,
                "tags-ignore",
                Value::Sequence(vec![string("**")]),
            );
        }
        if !workflow.trigger.paths.is_empty() {
            insert(
                &mut push,
                "paths",
                Value::Sequence(
                    workflow
                        .trigger
                        .paths
                        .iter()
                        .map(|value| string(value))
                        .collect(),
                ),
            );
        }
        insert(&mut trigger, "push", Value::Mapping(push));
    }
    if workflow.trigger.pull_request {
        insert(&mut trigger, "pull_request", Value::Mapping(Mapping::new()));
    }
    if workflow.trigger.workflow_dispatch {
        let mut dispatch = Mapping::new();
        if !workflow.physical.dispatch_inputs.is_empty() {
            let mut inputs = Mapping::new();
            for input in &workflow.physical.dispatch_inputs {
                let mut definition = Mapping::new();
                insert(&mut definition, "description", string(&input.description));
                insert(&mut definition, "required", Value::Bool(input.required));
                insert(&mut definition, "type", string(&input.kind));
                insert(&mut inputs, &input.id, Value::Mapping(definition));
            }
            insert(&mut dispatch, "inputs", Value::Mapping(inputs));
        }
        insert(&mut trigger, "workflow_dispatch", Value::Mapping(dispatch));
    }
    let merge = match workflow.trigger.merge_group {
        MergeGroup::Always => true,
        MergeGroup::Conditional => manifest.merge_queue,
        MergeGroup::Never => false,
    };
    if merge {
        insert(&mut trigger, "merge_group", Value::Mapping(Mapping::new()));
    }
    Value::Mapping(trigger)
}

fn concurrency(workflow: &Workflow) -> Value {
    let mut value = Mapping::new();
    insert(&mut value, "group", string(&workflow.concurrency.group));
    insert(
        &mut value,
        "cancel-in-progress",
        Value::Bool(workflow.concurrency.cancel_in_progress),
    );
    Value::Mapping(value)
}

fn jobs(manifest: &Manifest, workflow: &Workflow, inherited: &Permission) -> Value {
    let mut jobs = Mapping::new();
    for id in &workflow.jobs {
        let job = workflow.job_specs.get(id).expect("exact job inventory");
        let mut value = Mapping::new();
        insert(&mut value, "name", string(&job.physical_name));
        if let Some(condition) = &job.condition {
            insert(&mut value, "if", string(condition));
        }
        insert(&mut value, "runs-on", string(&job.runner));
        insert(
            &mut value,
            "timeout-minutes",
            Value::Number(job.timeout_minutes.into()),
        );
        if !job.needs.is_empty() {
            insert(
                &mut value,
                "needs",
                Value::Sequence(job.needs.iter().map(|need| string(need)).collect()),
            );
        }
        let expected_permission = manifest
            .permissions
            .get(&job.permission)
            .expect("permission reference checked");
        if expected_permission != inherited {
            insert(&mut value, "permissions", permission(expected_permission));
        }
        if !job.outputs.is_empty() {
            let mut outputs = Mapping::new();
            for (name, expression) in &job.outputs {
                insert(&mut outputs, name, string(expression));
            }
            insert(&mut value, "outputs", Value::Mapping(outputs));
        }
        let mut steps = Vec::new();
        for step in &job.steps {
            let mut rendered = Mapping::new();
            insert(&mut rendered, "name", string(&step.name));
            if let Some(id) = &step.id {
                insert(&mut rendered, "id", string(id));
            }
            if let Some(condition) = &step.condition {
                insert(&mut rendered, "if", string(condition));
            }
            match &step.operation {
                Operation::Run(invocation) => {
                    if let Some(directory) = &step.working_directory {
                        insert(&mut rendered, "working-directory", string(directory));
                    }
                    if invocation.credential == Credential::GithubToken {
                        let mut environment = Mapping::new();
                        insert(
                            &mut environment,
                            "GITHUB_TOKEN",
                            string("${{ github.token }}"),
                        );
                        insert(&mut rendered, "env", Value::Mapping(environment));
                    }
                    insert(
                        &mut rendered,
                        "run",
                        string(&render_invocation(
                            &invocation.executable,
                            &invocation.arguments,
                        )),
                    );
                }
                Operation::Action { action, inputs } => {
                    let action = manifest
                        .actions
                        .get(action)
                        .expect("action reference checked");
                    insert(
                        &mut rendered,
                        "uses",
                        string(&format!("{}@{}", action.repository, action.revision)),
                    );
                    if !inputs.is_empty() {
                        let mut with = Mapping::new();
                        for (name, value) in inputs {
                            insert(&mut with, name, string(value));
                        }
                        insert(&mut rendered, "with", Value::Mapping(with));
                    }
                }
            }
            steps.push(Value::Mapping(rendered));
        }
        insert(&mut value, "steps", Value::Sequence(steps));
        insert(&mut jobs, id, Value::Mapping(value));
    }
    Value::Mapping(jobs)
}

fn permission(permission: &Permission) -> Value {
    let mut value = Mapping::new();
    for (name, access) in [
        ("actions", permission.actions),
        ("contents", permission.contents),
        ("id-token", permission.id_token),
        ("attestations", permission.attestations),
        ("artifact-metadata", permission.artifact_metadata),
    ] {
        match access {
            Access::None => {}
            Access::Read => insert(&mut value, name, string("read")),
            Access::Write => insert(&mut value, name, string("write")),
        }
    }
    Value::Mapping(value)
}

pub(super) fn render_invocation(executable: &str, arguments: &[String]) -> String {
    std::iter::once(executable.to_owned())
        .chain(arguments.iter().map(|argument| render_argument(argument)))
        .collect::<Vec<_>>()
        .join(" ")
}

pub(super) fn render_argument(argument: &str) -> String {
    if let Some(reference) = argument.strip_prefix("$output:") {
        let mut components = reference.split('.');
        let owner = components.next().expect("validated output owner");
        let kind = components.next().expect("validated output kind");
        let output = components.next().expect("validated output name");
        return match kind {
            "artifact" => format!(
                "${{{{ needs.{owner}.outputs.{} }}}}",
                output.replace('-', "_")
            ),
            "action" => format!("${{{{ steps.{owner}.outputs.{output} }}}}"),
            _ => argument.to_owned(),
        };
    }
    argument.strip_prefix("$github:").map_or_else(
        || argument.to_owned(),
        |name| format!("${{{{ github.{name} }}}}"),
    )
}

fn insert(mapping: &mut Mapping, name: &str, value: Value) {
    mapping.insert(string(name), value);
}

fn string(value: &str) -> Value {
    Value::String(value.to_owned())
}
