[package]
name = "hell-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hell-builtins = { version = "0.1.0", path = "../hell-builtins" }
hell-core = { version = "0.1.0", path = "../hell-core" }
hell-host = { version = "0.1.0", path = "../hell-host" }
hell-http-host = { version = "0.1.0", path = "../hell-http-host" }
hell-types = { version = "0.1.0", path = "../hell-types" }

[dev-dependencies]
hell-compiler = { version = "0.1.0", path = "../hell-compiler" }
hell-source = { version = "0.1.0", path = "../hell-source" }

[[bin]]
name = "hell-runtime-process-fixture"
path = "test-support/process_fixture.rs"
test = false
bench = false
doc = false

[lints]
workspace = true
