[package]
name = "hell-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
compat-tracing = [
  "hell-compiler/compat-tracing",
  "hell-core/compat-tracing",
  "hell-runtime/compat-tracing",
]

[[bin]]
name = "hell"
path = "src/main.rs"

[dependencies]
hell-builtins = { version = "0.1.0", path = "../hell-builtins" }
hell-compiler = { version = "0.1.0", path = "../hell-compiler" }
hell-core = { version = "0.1.0", path = "../hell-core" }
hell-platform = { version = "0.1.0", path = "../hell-platform" }
hell-runtime = { version = "0.1.0", path = "../hell-runtime" }

[lints]
workspace = true
