[package]
name = "hell-ci-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[package.metadata.assurance]
cargo-fuzz-version = "0.13.2"
cargo-fuzz-toolchain = "nightly-2026-07-31"

[dependencies]
libfuzzer-sys = "0.4"
hell-builtins = { path = "../../hell-builtins" }
hell-digest = { path = "../../hell-digest" }
hell-testkit = { path = "../../hell-testkit", features = ["compat-tracing"] }

[[bin]]
name = "requirement_toml"
path = "fuzz_targets/requirement_toml.rs"
test = false
doc = false
bench = false

[[bin]]
name = "normalizer_toml"
path = "fuzz_targets/normalizer_toml.rs"
test = false
doc = false
bench = false

[[bin]]
name = "divergence_toml"
path = "fuzz_targets/divergence_toml.rs"
test = false
doc = false
bench = false

[[bin]]
name = "normalizer_replay"
path = "fuzz_targets/normalizer_replay.rs"
test = false
doc = false
bench = false

[[bin]]
name = "semantic_trace"
path = "fuzz_targets/semantic_trace.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
